export default {
    GET_COMPANY_LIST:'GET_COMPANY_LIST',
    GET_COMPANY_LIST_BY_ID:'GET_COMPANY_LIST_BY_ID',
    CREATE_COMPANY_LIST:'CREATE_COMPANY_LIST',
    UPDATE_COMPANY_LIST:'UPDATE_COMPANY_LIST',
    ADD_USERS_TO_COMPANY:'ADD_USERS_TO_COMPANY',
    REMOVE_USERS_TO_COMPANY:'REMOVE_USERS_TO_COMPANY',
    DELETE_COMPANY:'DELETE_COMPANY'
}