export default {
    GET_USERS_LIST:'GET_USERS_LIST',
    GET_USERS_LIST_BY_ID:'GET_USERS_LIST_BY_ID',
    CREATE_USERS_LIST:'CREATE_USERS_LIST',
    UPDATE_USERS_LIST:'UPDATE_USERS_LIST',
    DELETE_USERS:'DELETE_USERS',
    DEACTIVATE_USERS:'DEACTIVATE_USERS',
    GET_USER_BY_COMPANY_ID:'GET_USER_BY_COMPANY_ID'
}